# Generated by Django 6.0.4 on 2026-04-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Pritech ICT Solutions', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0.165, max_digits=5)),
                ('currency', models.CharField(default='MWK', max_length=10)),
                ('currency_symbol', models.CharField(default='K', max_length=5)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('mobile_money', models.CharField(blank=True, max_length=50)),
                ('invoice_footer', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
