# Generated by Django 5.2.7 on 2026-05-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client_feedback',
            field=models.TextField(blank=True, help_text="Client's rejection reason or change request"),
        ),
    ]
