# Generated by Django 5.2.7 on 2026-04-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='billing_type',
            field=models.CharField(choices=[('one_time', 'One Time'), ('recurring', 'Recurring')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('services', models.ManyToManyField(related_name='packages', to='services.service')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
