# Generated by Django 5.2.7 on 2026-05-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('viewer', 'Viewer'), ('billing', 'Billing')], default='viewer', help_text='Role within the client organization (only for client users)', max_length=20),
        ),
    ]
