# Generated by Django 5.2.7 on 2026-05-27 23:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationtoken'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('viewer', 'Viewer'), ('billing', 'Billing')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientorganization')),
            ],
        ),
    ]
