# Generated by Django 5.2.7 on 2026-05-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, default='Smart ICT Solutions for Modern Businesses', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='From managed IT support to custom software, we deliver technology that drives growth.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('about_title', models.CharField(blank=True, default='Your Trusted Technology Partner', max_length=200)),
                ('about_text', models.TextField(blank=True, default='We are a team of passionate engineers, developers, and support specialists dedicated to solving business problems with technology. With over a decade of experience, we deliver reliable ICT infrastructure, software solutions, and round‑the‑clock support.')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('projects_count', models.PositiveIntegerField(default=150)),
                ('satisfaction_percent', models.PositiveIntegerField(default=98)),
                ('support_hours', models.PositiveIntegerField(default=24)),
                ('years_experience', models.PositiveIntegerField(default=12)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('footer_copyright', models.CharField(blank=True, default='All Right Reserved.', max_length=200)),
            ],
            options={
                'verbose_name': 'Portfolio Settings',
                'verbose_name_plural': 'Portfolio Settings',
            },
        ),
    ]
