# Generated by Django 5.2.7 on 2026-05-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='265888888888', help_text="International format without '+' or with '+', e.g., 265888888888 or +265888888888", max_length=20),
        ),
    ]
