# Generated by Django 5.2.7 on 2026-06-03 10:49

import django.core.validators
import django.db.models.deletion
import portfolio.models
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfoliosettings_whatsapp_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInquiry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-20 digits, optional +).', regex='^\\+?[\\d\\s\\-\\(\\)]{7,20}$')])),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical inquiry',
                'verbose_name_plural': 'historical Inquiries',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNewsletterSubscriber',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('subscribed_at', models.DateTimeField(blank=True, editable=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Newsletter Subscriber',
                'verbose_name_plural': 'historical Newsletter Subscribers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPortfolioProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', portfolio.models.SanitizingQuillField(blank=True)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('technologies', models.CharField(blank=True, max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical portfolio project',
                'verbose_name_plural': 'historical portfolio projects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPortfolioSettings',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, default='Smart ICT Solutions for Modern Businesses', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='From managed IT support to custom software, we deliver technology that drives growth.')),
                ('hero_image', models.TextField(blank=True, max_length=100, null=True, validators=[portfolio.models.validate_image_size])),
                ('about_title', models.CharField(blank=True, default='Your Trusted Technology Partner', max_length=200)),
                ('about_text', models.TextField(blank=True, default='We are a team of passionate engineers, developers, and support specialists dedicated to solving business problems with technology.')),
                ('about_image', models.TextField(blank=True, max_length=100, null=True, validators=[portfolio.models.validate_image_size])),
                ('projects_count', models.PositiveIntegerField(default=150)),
                ('satisfaction_percent', models.PositiveIntegerField(default=98)),
                ('support_hours', models.PositiveIntegerField(default=24)),
                ('years_experience', models.PositiveIntegerField(default=12)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, default='265888888888', help_text="International format without '+' or with '+', e.g., 265888888888 or +265888888888", max_length=20)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('footer_copyright', models.CharField(blank=True, default='All Right Reserved.', max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Portfolio Settings',
                'verbose_name_plural': 'historical Portfolio Settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-20 digits, optional +).', regex='^\\+?[\\d\\s\\-\\(\\)]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='description',
            field=portfolio.models.SanitizingQuillField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', validators=[portfolio.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='about_text',
            field=models.TextField(blank=True, default='We are a team of passionate engineers, developers, and support specialists dedicated to solving business problems with technology.'),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', validators=[portfolio.models.validate_image_size]),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['created_at'], name='portfolio_i_created_92347a_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['is_read'], name='portfolio_i_is_read_6713ec_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscriber',
            index=models.Index(fields=['subscribed_at'], name='portfolio_n_subscri_3702d7_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscriber',
            index=models.Index(fields=['is_confirmed'], name='portfolio_n_is_conf_d6b9ad_idx'),
        ),
        migrations.AddField(
            model_name='historicalinquiry',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnewslettersubscriber',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalportfolioproject',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalportfoliosettings',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
